// Build-time content. Provenance and snapshot decisions: CONTENT_SOURCES.md.
export const SITE_CONFIG = {
  person: {
    name: "Pratham Pandey",
    location: "INDIA",
    email: "pratham07work@gmail.com",
    instagram:
      "https://www.instagram.com/pratham07.io?stkn=MW5ueG1oOW4wanZvZA%3D%3D&utm_source=qr",
    github: "https://github.com/bbethical010-glitch",
    linkedin: "https://www.linkedin.com/in/pratham-pandey-132a77384",
  },
  projects: [
    {
      slug: "meme-capsule",
      index: "01",
      name: "Meme Capsule",
      short: "MEME / CAPSULE",
      status: "Released / active",
      released: true,
      tagline: "One tap. One meme. Zero fluff.",
      overview:
        "A mobile-first meme delivery product built around a single-action capsule rather than an infinite feed. The product pairs a public web platform and Android app with serverless edge delivery and a curation system.",
      role: "Original ideator & lead frontend",
      platform: "Android + Web",
      timeframe: "2026 / evolving releases",
      stack: [
        "React",
        "TypeScript",
        "Vite",
        "Capacitor",
        "Cloudflare Pages",
        "D1",
        "R2",
      ],
      features: [
        "Single-tap meme capsule flow",
        "Card deck with gesture interaction",
        "Meme Vault and Mood Boards",
        "Native MediaStore saving and sharing",
        "Edge delivery with Cloudflare D1 and R2",
        "Curation, safety, and reporting systems",
      ],
      gallery: [
        {
          label: "Splash & App Entry",
          image: "assets/images/meme-capsule/loading-screen.jpg",
        },
        {
          label: "Capsule Dispenser",
          image: "assets/images/meme-capsule/home-screen.jpg",
        },
        {
          label: "Active Meme Card",
          image: "assets/images/meme-capsule/meme-loaded.jpg",
        },
        { label: "Meme Vault", image: "assets/images/meme-capsule/vault.jpg" },
        {
          label: "Mood Boards",
          image: "assets/images/meme-capsule/moodboards.jpg",
        },
      ],
      architecture: {
        specId: "SPEC-MC // DOCUMENTED DESIGN",
        note: "A gesture-driven client uses a rolling prefetch queue to reduce waiting while Cloudflare handles content delivery. The supplied mobile v3.4 snapshot describes React 19, Capacitor 8, and a 12-item queue target; the separate web frontend uses React 18. Queue depth varies during use.",
        nodes: [
          {
            id: "client",
            name: "Android & Web Client",
            tag: "FRONTEND / UI",
            tech: "React / Capacitor 8 on Android",
            protocol: "HTTPS + Android Java bridge",
            behavior: "Gesture-driven card stack",
            desc: "The Android client uses React 19 and Capacitor 8; the web frontend uses React 18. A native MediaStore bridge supports saving images, alongside a local vault and mood boards.",
            log: "Gesture dispatch: user tap captured -> invoking prefetch buffer",
          },
          {
            id: "edge",
            name: "Cloudflare Edge Gateway",
            tag: "NETWORK / ROUTER",
            tech: "Pages + Workers Runtime",
            protocol: "HTTPS / Pages Functions",
            behavior: "Serverless content API",
            desc: "Cloudflare Pages Functions query curated content and handle client events. Backend engineering and curation are separate from Pratham's frontend and native-client role.",
            log: "Example: request the next eligible curated meme",
          },
          {
            id: "storage",
            name: "Cloudflare D1 & R2",
            tag: "DATA / MEDIA LAKE",
            tech: "Serverless SQLite + R2 Bucket",
            protocol: "S3 API + SQL Prepared Stmt",
            behavior: "Metadata and media separated",
            desc: "D1 stores structured metadata and curation state; R2 stores media objects. The client receives eligible media through the delivery API.",
            log: "Example: retrieve curated metadata and its media object",
          },
          {
            id: "prefetch",
            name: "Client Prefetch Queue",
            tag: "PIPELINE / BUFFER",
            tech: "Async client-side fetching",
            protocol: "Memory Queue Buffer",
            behavior: "12-item rolling queue target",
            desc: "The supplied v3.4 mobile snapshot targets a 12-item FIFO queue and replenishes it during consumption. This is a buffering strategy, not a guarantee of zero latency or uninterrupted connectivity.",
            log: "Example: enqueue a fetched meme for the next interaction",
          },
        ],
        pipeline: [
          {
            step: "01",
            name: "User Action",
            desc: "User triggers single-tap capsule dispenser or swipe gesture.",
          },
          {
            step: "02",
            name: "Prefetch Pop",
            desc: "Display an available card from the rolling client queue.",
          },
          {
            step: "03",
            name: "Edge Replenish",
            desc: "Asynchronous requests replenish the queue through the Cloudflare content API.",
          },
          {
            step: "04",
            name: "Native Save",
            desc: "1-tap save writes directly to Android MediaStore via native Java bridge.",
          },
        ],
        highlights: [
          {
            label: "Storage Decoupling",
            value: "Media served via R2 with zero bandwidth tax",
          },
          {
            label: "Buffered UI",
            value:
              "A rolling queue reduces dependence on each network round trip",
          },
          {
            label: "Native Bridge",
            value: "Custom Android MediaStore Java plugin",
          },
        ],
        edges: [
          ["client", "prefetch", "Consume queued cards"],
          ["prefetch", "edge", "Request replenishment"],
          ["edge", "storage", "Query metadata and media"],
        ],
        flows: [
          {
            name: "Fetch and display",
            steps: [
              "client",
              "prefetch",
              "edge",
              "storage",
              "edge",
              "prefetch",
              "client",
            ],
          },
        ],
      },
      website: "https://memecapsule.wtf/",
      download:
        "https://play.google.com/store/apps/details?id=com.meme.capsule&referrer=utm_source%3Dwebsite%26utm_medium%3Dhero_badge",
      instagram:
        "https://www.instagram.com/capsule.meme?utm_source=ig_web_button_share_sheet&stkn=ZDNlZDc0MzIxNw==",
      accent: "#9b30ff",
    },
    {
      slug: "easy-storage-cloud",
      index: "02",
      name: "Easy Storage Cloud",
      short: "YOUR / CLOUD",
      status: "In development",
      released: false,
      tagline: "Your phone is your cloud.",
      overview:
        "A peer-to-peer personal cloud where an Android phone and its attached storage remain the source of truth. A public relay provides reachability and signaling, rather than becoming the primary file store.",
      role: "Product & systems builder",
      platform: "Android + Web",
      timeframe: "2026",
      stack: [
        "Kotlin",
        "Jetpack Compose",
        "Ktor",
        "WebRTC",
        "WebSockets",
        "Render",
      ],
      features: [
        "Native Remote File Explorer",
        "Real-time search and multi-attribute sorting",
        "Bidirectional chunked file transfers",
        "Foreground service and transfer notifications",
        "Role-based access and token handshake",
        "WebRTC signaling with proxy fallback",
      ],
      gallery: ["Remote file explorer", "P2P connection", "Transfer activity"],
      architecture: {
        specId: "SPEC-ESC // P2P VAULT",
        note: "The phone and attached drive remain the primary file store. Signaling establishes a direct WebRTC path when possible; TURN or an HTTP/WebSocket proxy may relay bytes when a direct connection is unavailable.",
        nodes: [
          {
            id: "client",
            name: "Remote Explorer Client",
            tag: "INTERFACE / PEER",
            tech: "Web UI / Compose App",
            protocol: "WebRTC DataChannel",
            behavior: "Remote browsing and transfers",
            desc: "Virtual remote file tree offering real-time search, sorting, folder expansion, and chunked upload/download streaming directly to the host device.",
            log: "Remote peer init: requesting session auth -> generating ephemeral token",
          },
          {
            id: "relay",
            name: "Signaling & Relay Bridge",
            tag: "COORDINATOR / NAT",
            tech: "Ktor WebSockets (Render)",
            protocol: "WSS / STUN / TURN",
            behavior: "Signaling with relay fallback",
            desc: "Brokers SDP and ICE exchange. Configured TURN servers or the HTTP/WebSocket proxy carry traffic when needed; connectivity depends on network conditions and deployment configuration.",
            log: "Example: exchange signaling or forward a fallback request",
          },
          {
            id: "host",
            name: "Host Phone Daemon",
            tag: "NODE / STORAGE CORE",
            tech: "Android Background Service",
            protocol: "Ktor Local HTTP :8080",
            behavior: "Foreground-service hosting",
            desc: "Runs an embedded Ktor HTTP server inside a persistent Android foreground service, managing peer authentication tokens with 24-hour expiration.",
            log: "Node daemon: active on port 8080 -> token verified (Role: Manager)",
          },
          {
            id: "storage",
            name: "Attached Physical Drive",
            tag: "PHYSICAL STORAGE",
            tech: "USB-C SSD / MicroSD (SAF)",
            protocol: "Android SAF / Direct I/O",
            behavior: "Device-owned primary storage",
            desc: "Storage is accessed through Android's Storage Access Framework. Files remain stored on the device or attached drive, while transfer bytes can pass through relay infrastructure on fallback paths.",
            log: "I/O subsystem: direct SAF chunk stream open -> reading local block",
          },
        ],
        pipeline: [
          {
            step: "01",
            name: "Handshake",
            desc: "Client scans QR or enters share code to connect with relay.",
          },
          {
            step: "02",
            name: "Negotiate a Route",
            desc: "Peers exchange ICE candidates and attempt a direct connection using the configured network services.",
          },
          {
            step: "03",
            name: "Direct or Relayed",
            desc: "Use a direct WebRTC DataChannel when available, or TURN / HTTP proxy fallback when required.",
          },
          {
            step: "04",
            name: "Transfer Files",
            desc: "The host reads or writes device storage and transfers data over the selected route.",
          },
        ],
        highlights: [
          {
            label: "Device-Owned Storage",
            value:
              "The relay provides reachability rather than becoming the primary file store",
          },
          {
            label: "Carrier NAT Traversal",
            value: "WebSockets signaling + TURN fallback",
          },
          {
            label: "Role Handshake",
            value: "Viewer, Contributor, Manager, Admin access tiers",
          },
        ],
        edges: [
          ["client", "relay", "Signaling / fallback traffic"],
          ["relay", "host", "Signaling / fallback traffic"],
          ["client", "host", "Direct WebRTC when available"],
          ["host", "storage", "Device file access"],
        ],
        flows: [
          {
            name: "Direct transfer after signaling",
            steps: ["client", "host", "storage", "host", "client"],
          },
          {
            name: "Relayed transfer",
            steps: [
              "client",
              "relay",
              "host",
              "storage",
              "host",
              "relay",
              "client",
            ],
          },
        ],
      },
      website: null,
      download: null,
      note: "Easy Storage Cloud is a working name and may change before launch.",
      accent: "#3b82f6",
    },
    {
      slug: "convertix",
      index: "03",
      name: "Convertix",
      short: "Convertix",
      status: "Active rebuild",
      released: false,
      tagline:
        "A Flutter media and document conversion app for Android and iOS.",
      overview:
        "A Flutter media and document conversion app for Android and iOS. Media processing is performed on-device without internet, while document conversion runs through a FastAPI and LibreOffice backend.",
      role: "App concept & implementation direction",
      platform: "ANDROID + iOS",
      timeframe: "v1.0.9 / rebuild",
      stack: [
        "Flutter",
        "Dart",
        "Riverpod",
        "FFmpegKit",
        "Dio",
        "FastAPI",
        "LibreOffice",
        "Hive",
      ],
      features: [
        "Image format conversion",
        "Video-to-audio extraction",
        "Audio and video conversion",
        "LOG/HDR video compression",
        "PDF and document tools",
        "History and shared output handling",
      ],
      gallery: ["Media tools", "Document tools", "Conversion history"],
      architecture: {
        specId: "SPEC-CVX // HYBRID ENGINE",
        note: "Media tools process files on-device. Document tools use a separate FastAPI and LibreOffice service. These are alternative processing branches, with results recorded in local conversion history.",
        nodes: [
          {
            id: "client",
            name: "Flutter Application",
            tag: "CLIENT / STATE CORE",
            tech: "Flutter + Riverpod",
            protocol: "Plugin calls / HTTPS",
            behavior: "Asynchronous task state",
            desc: "AsyncNotifier architecture manages conversion queues, cancel tokens, format validations, and batch progress tracking without UI blocking.",
            log: "Task created: video transcode job queued -> analyzing codec header",
          },
          {
            id: "ffmpeg",
            name: "On-Device Media Engine",
            tag: "LOCAL RUNTIME / ZERO NET",
            tech: "FFmpegKit + Dart image tools",
            protocol: "Flutter plugin / local I/O",
            behavior: "Offline media processing",
            desc: "FFmpegKit handles audio/video conversion and compression, while Dart image tools handle image operations. Processing time and available codecs depend on the device and build.",
            log: "Example: process a media file on the device",
          },
          {
            id: "hive",
            name: "Local Hive Persistence",
            tag: "EMBEDDED STORAGE",
            tech: "Hive NoSQL Binary Box",
            protocol: "Direct Binary I/O",
            behavior: "Local conversion history",
            desc: "Hive stores conversion history and output metadata for completed tasks.",
            log: "Local DB: output metadata saved to Hive box -> cache pointer stored",
          },
          {
            id: "backend",
            name: "Cloud Document Worker",
            tag: "BACKEND / DOCUMENTS",
            tech: "FastAPI + Headless LibreOffice",
            protocol: "HTTPS / Multipart REST",
            behavior: "Temporary document processing",
            desc: "FastAPI invokes document tools including headless LibreOffice and PyMuPDF. The supplied architecture specifies deletion within 30 seconds; this portfolio does not verify the deployed service's retention behavior.",
            log: "Doc worker: multipart received -> LibreOffice headless render complete",
          },
        ],
        pipeline: [
          {
            step: "01",
            name: "Format Inspection",
            desc: "Client validates file MIME type and routes to local or cloud engine.",
          },
          {
            step: "02",
            name: "Local Media Branch",
            desc: "Media tools process supported formats on the device without uploading media to the document service.",
          },
          {
            step: "03",
            name: "Document Branch",
            desc: "Document tools send supported inputs to FastAPI and LibreOffice instead of the local media engine.",
          },
          {
            step: "04",
            name: "Result and History",
            desc: "The client receives the result and stores history locally. Backend cleanup follows the documented retention design.",
          },
        ],
        highlights: [
          {
            label: "Zero-Data Media",
            value: "Media never leaves phone: 100% offline FFmpeg",
          },
          {
            label: "Temporary Documents",
            value: "The backend design specifies short-lived processing files",
          },
          {
            label: "Async State",
            value: "Riverpod AsyncNotifier with job cancel tokens",
          },
        ],
        edges: [
          ["client", "ffmpeg", "Local media processing"],
          ["client", "backend", "Remote document processing"],
          ["client", "hive", "Save result metadata"],
        ],
        flows: [
          {
            name: "Local media conversion",
            steps: ["client", "ffmpeg", "client", "hive"],
          },
          {
            name: "Document conversion",
            steps: ["client", "backend", "client", "hive"],
          },
        ],
      },
      website: null,
      download:
        "https://play.google.com/store/apps/details?id=com.allformat.converter&pcampaignid=web_share",
      instagram: null,
      note: "Current documentation identifies Play Store signing and Android API 36 requirements as blockers before the next release.",
      accent: "#6d3ee8",
    },
  ],
};
