import { SITE_CONFIG as cfg } from "../js/config.js";

const e = (value) =>
  String(value).replace(
    /[&<>"']/g,
    (char) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        char
      ],
  );
const projectPath = (root, slug) => `${root}projects/${slug}/index.html`;
const external = (label, url, className = "") =>
  url
    ? `<a class="${className}" href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(label)}</a>`
    : "";
const heading = (first, second) =>
  `<h2 class="section-heading"><span class="line"><span>${e(first)}</span></span><span class="line"><span>${e(second)}</span></span></h2>`;
const ticker = (text) =>
  `<div class="ticker" aria-hidden="true"><div class="ticker__run">${e(`${text} • `.repeat(4))}</div></div>`;
const badge = (project) =>
  `<span class="status-badge ${project.released ? "" : "is-progress"}">${e(project.status)}</span>`;

export function picture(
  image,
  alt,
  root,
  manifest,
  { lazy = true, sizes = "(max-width: 420px) 76vw, 320px" } = {},
) {
  const meta = manifest[image];
  if (!meta?.sources.length)
    throw new Error(`Run npm run images: missing image metadata for ${image}`);
  return `<picture><source type="image/webp" srcset="${meta.sources.map((source) => `${root}${source.src} ${source.width}w`).join(", ")}" sizes="${e(sizes)}"><img src="${root}${image}" alt="${e(alt)}" width="${meta.width}" height="${meta.height}" loading="${lazy ? "lazy" : "eager"}" ${lazy ? "" : 'fetchpriority="high"'} decoding="async"></picture>`;
}

export function shell({
  title,
  description,
  root,
  body,
  script = "shared",
  theme = "",
  canonical = "",
  socialImage = "",
}) {
  const nav = `<a data-transition href="${root}index.html#projects">Projects</a><a data-transition href="${root}about/index.html">About</a><a href="mailto:${e(cfg.person.email)}">Contact</a>`;
  const socials = ["github", "linkedin", "instagram"]
    .map((key) =>
      external(
        { github: "GitHub", linkedin: "LinkedIn", instagram: "Instagram" }[key],
        cfg.person[key],
      ),
    )
    .join("");
  return `<!doctype html><html lang="en"><head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="${e(description)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:type" content="website">
    ${canonical ? `<link rel="canonical" href="${e(canonical)}"><meta property="og:url" content="${e(canonical)}">` : ""}
    ${socialImage ? `<meta property="og:image" content="${e(socialImage)}">` : ""}
    <title>${e(title)}</title><link rel="icon" href="${root}assets/favicon.svg" type="image/svg+xml">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:opsz,wght@6..96,700;6..96,800&family=Pirata+One&family=Playfair+Display:wght@600;700&family=Source+Serif+4:opsz,wght@8..60,300;8..60,400;8..60,600&display=swap" rel="stylesheet">
    ${["tokens", "themes", "pages"].map((name) => `<link rel="stylesheet" href="${root}css/${name}.css">`).join("")}
  </head><body ${theme ? `data-theme="${e(theme)}"` : ""}>
    <!-- Generated by scripts/build.mjs. Edit scripts/pages.mjs or js/config.js. -->
    <a class="skip-link" href="#main">Skip to content</a>
    <header class="shell-header"><nav class="header-bar" aria-label="Primary">
      <span class="header-location">[${e(cfg.person.location)}]</span><a class="header-name" href="${root}index.html">${e(cfg.person.name)}</a>
      <span class="header-links">${nav}</span><button class="menu-button" type="button" aria-expanded="false" aria-controls="site-menu" hidden>Menu <i aria-hidden="true"></i></button>
    </nav></header>
    <main id="main" tabindex="-1">${body}</main>
    <footer class="footer"><p class="footer__headline">Open to internship opportunities.</p><div class="footer__right"><a href="mailto:${e(cfg.person.email)}">${e(cfg.person.email)}</a>${socials}</div><div class="footer__lower"><span>© <span data-year>2026</span> ${e(cfg.person.name)}</span><span>Designed as a digital broadsheet</span></div></footer>
    <dialog class="menu-overlay" id="site-menu" aria-labelledby="menu-title"><div class="menu-overlay__top"><h2 id="menu-title">Site menu</h2><button class="menu-close" type="button" autofocus>Close ×</button></div><nav class="menu-links" aria-label="Site menu">${nav}</nav><div class="menu-social">${socials}</div></dialog>
    <script src="${root}js/gsap.min.js" defer></script><script src="${root}js/ScrollTrigger.min.js" defer></script><script src="${root}js/lenis.min.js" defer></script><script type="module" src="${root}js/${script}.js"></script>
  </body></html>`;
}

export function home(manifest) {
  const cards = cfg.projects
    .map(
      (p, index) =>
        `<article class="swipe-card" data-index="${index}" data-slug="${p.slug}" aria-label="${e(p.name)}, ${index + 1} of ${cfg.projects.length}" aria-roledescription="slide" tabindex="${index ? -1 : 0}" ${index ? "inert" : ""} style="--project-accent:${p.accent}"><div class="swipe-card__art"><span>${e(p.short)}</span><small>${e(p.platform)}</small></div><div class="swipe-card__body"><h3>${e(p.name)}</h3>${badge(p)}<p>${e(p.tagline)}</p><a data-transition class="editorial-link" href="${projectPath("", p.slug)}">Read the case study ↗</a></div></article>`,
    )
    .join("");
  const copies = cfg.projects
    .map(
      (p, index) =>
        `<div data-project-copy="${p.slug}" ${index ? "hidden" : ""}><span class="eyebrow">Now reading / ${p.index}</span><h3>${e(p.name)}</h3><p>${e(p.overview)}</p><span class="byline">${e(p.role)}</span></div>`,
    )
    .join("");
  const grid = cfg.projects
    .map(
      (p) =>
        `<a data-transition class="project-grid__card" href="${projectPath("", p.slug)}" style="--project-accent:${p.accent}"><div class="project-grid__art">${e(p.short)}</div><span class="eyebrow">${p.index} / ${e(p.status)}</span><h3>${e(p.name)}</h3><p>${e(p.tagline)}</p><span class="editorial-link">Read the case study ↗</span></a>`,
    )
    .join("");
  const skills = [
    ["Mobile product interfaces", "Flutter / Compose / Capacitor"],
    ["Frontend systems", "React / TypeScript / Vite"],
    ["Media processing", "FFmpegKit"],
    ["Backend services", "FastAPI / Ktor / Dio"],
    ["Edge platform", "Cloudflare Pages / D1 / R2"],
    ["P2P transport", "WebRTC / WebSockets"],
    ["State & local data", "Riverpod / Hive"],
    ["Product & systems thinking", "Architecture / implementation plans"],
  ];
  return `<section class="home-hero" aria-labelledby="hero-title">
    <h1 id="hero-title" class="home-hero__name" aria-label="Pratham Pandey">${["PRATHAM", "PANDEY"].map((word) => `<span class="hero-word" aria-hidden="true">${[...word].map((letter) => `<span class="hero-letter">${letter}</span>`).join("")}</span>`).join("")}</h1>
    <div class="hero-triad"><figure class="hero-photo">${picture("assets/images/pratham-1.jpg", "Portrait of Pratham Pandey", "", manifest, { lazy: false, sizes: "(max-width: 820px) 50vw, 30vw" })}<figcaption>Pratham Pandey / 01</figcaption></figure><div class="hero-statement"><div><h2>Student,<br>builder,<br>maker of apps.</h2><p>BCom / multidisciplinary / India</p></div></div><figure class="hero-photo">${picture("assets/images/pratham-2.jpg", "Pratham Pandey, builder", "", manifest, { sizes: "(max-width: 820px) 50vw, 30vw" })}<figcaption>Pratham Pandey / 02</figcaption><span class="hero-stamp" aria-hidden="true">PRATHAM<br>PANDEY<br>MADE IT</span></figure></div>
    ${ticker("Student builder • India • Open to internships • Apps / backends / videos / business models")}
    </section><section class="section home-bio" id="about"><div><span class="eyebrow">About / 01</span>${heading("Curious on", "purpose.")}</div><div class="bio-copy"><p class="dropcap">I’m a first-semester BCom student who builds apps, backends, videos, and business models alongside coursework.</p><p>I like taking an idea seriously enough to understand its interface, its system, and the real constraints behind it.</p><a data-transition class="editorial-link" href="about/index.html">More about my approach ↗</a></div><aside class="bio-aside"><strong>PP</strong>From coursework to working prototypes. Open to internships where curiosity and ownership matter.</aside></section>
    <section class="display-banner"><h2>SELECTED / WORK /</h2></section>
    <section class="section swipe-selector" aria-label="Project selector" aria-roledescription="carousel" hidden><div class="selector-wrap"><div><p class="eyebrow" id="selector-help">Drag a card, use the arrow buttons, or press left and right arrow keys.</p><div id="card-stage" class="card-stage" aria-describedby="selector-help">${cards}</div><div class="swipe-controls"><button id="previous-card" type="button" aria-label="Previous project">←</button><button id="next-card" type="button" aria-label="Next project">→</button></div><p id="selector-status" class="sr-only" role="status" aria-atomic="true"></p></div><aside id="selector-copy" class="selector-copy">${copies}</aside></div></section>
    <section class="section section-rule" id="projects" aria-labelledby="projects-title"><h2 class="eyebrow" id="projects-title">All projects</h2><div id="project-grid" class="project-grid">${grid}</div></section>
    <section class="display-banner"><h2>TOOLS / INDEX /</h2></section><section class="section"><h2 class="eyebrow">Skills from the documented builds</h2><ul class="skills-index">${skills.map(([label, stack]) => `<li>${label}<span>${stack}</span></li>`).join("")}</ul></section>`;
}

export function about(manifest) {
  const principles = [
    [
      "Start with the experience.",
      "Whether it is a meme app, a storage node, or a converter, the aim is a focused interaction that makes sense quickly.",
    ],
    [
      "Read the system too.",
      "I work beyond the interface by learning the architecture, flows, services, storage, and deployment assumptions that make a product work.",
    ],
    [
      "Build while studying.",
      "Coursework and practical work are part of the same practice: learn the foundations, then test ideas in real projects.",
    ],
  ];
  return `<section class="project-hero"><div class="project-hero__inner"><span class="eyebrow">About / Pratham Pandey</span><h1>Built from curiosity.</h1><p class="project-hero__tagline">A first-semester BCom student learning business while making things that need both a point of view and a working system.</p></div></section>${ticker("Apps • backends • videos • business models • open to internships")}<section class="section about-page"><div><p class="about-page__lead">I care about useful constraints: what a user needs, what a device can do, and what a product needs to become real.</p><figure class="hero-photo about-portrait">${picture("assets/images/pratham-1.jpg", "Portrait of Pratham Pandey", "../", manifest, { sizes: "(max-width: 820px) calc(100vw - 40px), 520px" })}<figcaption>Pratham Pandey / 2026</figcaption></figure></div><div class="principles">${principles.map(([title, text], i) => `<article class="principle"><b>0${i + 1}</b><div><h2>${title}</h2><p>${text}</p></div></article>`).join("")}</div></section><section class="section section-rule"><span class="eyebrow">Now looking for</span>${heading("An internship", "with room to build.")}<a class="button" href="mailto:${e(cfg.person.email)}">Email Pratham ↗</a></section>`;
}

function architecture(arch) {
  const positions = [
    { x: 18, y: 28 },
    { x: 287, y: 28 },
    { x: 287, y: 218 },
    { x: 18, y: 218 },
  ];
  const nodeMap = new Map(
    arch.nodes.map((node, index) => [
      node.id,
      { ...node, ...positions[index] },
    ]),
  );
  const wires = arch.edges
    .map(([from, to, label]) => {
      const a = nodeMap.get(from),
        b = nodeMap.get(to);
      const dx = b.x - a.x,
        dy = b.y - a.y;
      const scale = 1 / Math.max(Math.abs(dx) / 107.5, Math.abs(dy) / 37);
      return `<path class="arch-wire" d="M ${a.x + 107.5 + dx * scale} ${a.y + 37 + dy * scale} L ${b.x + 107.5 - dx * scale} ${b.y + 37 - dy * scale}" marker-end="url(#arch-arrow)"><title>${e(label)}</title></path>`;
    })
    .join("");
  const nodes = arch.nodes
    .map(
      (node, i) =>
        `<g class="arch-node-group" data-node="${node.id}" transform="translate(${positions[i].x}, ${positions[i].y})" aria-label="${e(node.name)}"><g class="arch-node-visual"><rect class="arch-node-box" width="215" height="74" rx="3"></rect><text class="arch-node-tag" x="12" y="20">${e(node.tag)}</text><text class="arch-node-title" x="12" y="42">${e(node.name)}</text><text class="arch-node-sub" x="12" y="58">${e(node.tech)}</text></g></g>`,
    )
    .join("");
  const details = arch.nodes
    .map(
      (node) =>
        `<article class="arch-hud" id="detail-${node.id}" data-detail="${node.id}"><div class="arch-hud__header"><span class="arch-hud__tag">${e(node.tag)}</span><h4 class="arch-hud__name">${e(node.name)}</h4><span class="arch-hud__tech">${e(node.tech)}</span></div><p class="arch-hud__desc">${e(node.desc)}</p><div class="arch-hud__meta-grid"><div class="arch-meta-item"><span>Interface</span><b>${e(node.protocol)}</b></div><div class="arch-meta-item"><span>Design</span><b>${e(node.behavior)}</b></div></div><div class="arch-console-log"><p><span class="log-prompt">Example event:</span> ${e(node.log.replace(/^Example: /, ""))}</p></div></article>`,
    )
    .join("");
  return `<div class="arch-console" id="arch-console"><div class="arch-topbar"><div class="arch-badge-group"><span class="arch-spec-pill">${e(arch.specId)}</span><span class="arch-status">ILLUSTRATIVE MODEL</span></div><div class="arch-controls" hidden><div class="arch-views-nav" aria-label="Architecture views">${[
    ["schematic", "Topology"],
    ["pipeline", "Pipeline"],
    ["highlights", "Decisions"],
  ]
    .map(
      ([view, label]) =>
        `<button type="button" class="arch-tab-btn" id="tab-${view}" data-view="${view}">${label}</button>`,
    )
    .join("")}</div></div></div>
    <p class="arch-disclaimer">A documented system model. Walkthroughs are illustrative; they do not contact or verify a live service.</p>
    <section class="arch-view-panel" id="view-schematic"><h3 class="arch-panel-title">Topology</h3><div class="arch-workbench"><div class="arch-canvas-wrap"><div class="arch-diagram-scroll" tabindex="0" role="region" aria-label="System diagram. Scroll horizontally on smaller screens."><svg class="arch-svg-stage" viewBox="0 0 520 320" role="group" aria-label="System components"><defs><marker id="arch-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 Z" fill="currentColor"></path></marker></defs>${wires}${nodes}</svg></div><ul class="arch-connections">${arch.edges.map(([from, to, label]) => `<li><b>${e(nodeMap.get(from).name)} → ${e(nodeMap.get(to).name)}</b>: ${e(label)}</li>`).join("")}</ul></div><div class="arch-details">${details}</div></div><p id="node-status" class="sr-only" role="status" aria-atomic="true"></p></section>
    <section class="arch-view-panel" id="view-pipeline"><h3 class="arch-panel-title">Pipeline</h3><div class="arch-pipeline-wrap">${arch.pipeline.map((step) => `<div class="arch-pipeline-step"><b>${step.step}</b><h4>${e(step.name)}</h4><p>${e(step.desc)}</p></div>`).join("")}</div></section>
    <section class="arch-view-panel" id="view-highlights"><h3 class="arch-panel-title">Decisions</h3><div class="arch-highlights-wrap">${arch.highlights.map((item) => `<div class="arch-highlight-card"><span>${e(item.label)}</span><p>${e(item.value)}</p></div>`).join("")}</div></section>
    <div class="arch-demo" hidden><label for="flow-path">Example path</label><select id="flow-path">${arch.flows.map((flow) => `<option value="${flow.steps.join(",")}">${e(flow.name)}</option>`).join("")}</select><button type="button" class="arch-sim-btn" id="run-sim-btn">Show example flow</button><p id="flow-status" role="status" aria-atomic="true"></p></div>
  </div>`;
}

export function projectPage(project, next, manifest) {
  const root = "../../";
  const facts = [
    ["Role", project.role],
    ["Platform", project.platform],
    ["Stack", project.stack.slice(0, 2).join(" + ")],
    ["Timeframe", project.timeframe],
    ["Status", project.status],
  ];
  const screens = project.gallery
    .map((item, i) => {
      const label = typeof item === "string" ? item : item.label;
      return `<article class="screen">${item.image ? `<div class="screen__media">${picture(item.image, `${label} screenshot`, root, manifest)}</div><div class="screen__label"><span>0${i + 1}</span><span>${e(label)}</span></div>` : `<div class="screen__inside"><b>0${i + 1}</b><small>${e(label)}</small><p class="screen__placeholder">Interface concept<br>Screenshot pending</p></div>`}</article>`;
    })
    .join("");
  return `<section class="project-hero"><div class="project-hero__inner">${badge(project)}<h1>${e(project.name)}</h1><p class="project-hero__tagline">${e(project.tagline)}</p><div class="facts">${facts.map(([label, value]) => `<div class="fact"><span class="meta-label">${label}</span><b>${e(value)}</b></div>`).join("")}</div></div></section>${ticker(`${project.name} • ${project.tagline}`)}
    <section class="section case-overview"><div><span class="eyebrow">Overview / 01</span>${heading("The problem,", "the idea.")}</div><div><p>${e(project.overview)}</p>${project.note ? `<p class="bio-aside project-note"><strong>Note</strong>${e(project.note)}</p>` : ""}</div></section>
    <section class="section section-rule"><h2 class="eyebrow">Key features / 02</h2><ol class="case-feature-list">${project.features.map((feature, i) => `<li><span>0${i + 1}</span>${e(feature)}</li>`).join("")}</ol></section>
    <section class="display-banner"><h2>SCREEN / STUDIES /</h2></section><section class="section gallery-outer"><h2 class="eyebrow" id="gallery-title">${project.gallery.some((item) => item.image) ? "Interface studies / Real app screenshots" : "Interface concepts / Screenshots pending"}</h2><p class="gallery-hint" id="gallery-help">Scroll horizontally, swipe, or focus the gallery and use the arrow keys to see every screen.</p><div class="gallery-scroll" tabindex="0" role="region" aria-labelledby="gallery-title" aria-describedby="gallery-help"><div class="case-gallery">${screens}</div></div></section>
    <section class="section section-rule architecture"><div><span class="eyebrow">Architecture / 03</span>${heading("Systems", "with a point.")}<p class="diagram-note">${e(project.architecture.note)}</p></div>${architecture(project.architecture)}</section>
    <section class="section section-rule"><h2 class="eyebrow">Tech stack / 04</h2><div class="stack">${project.stack.map((item) => `<span>${e(item)}</span>`).join("")}</div></section>
    <section class="section section-rule"><span class="eyebrow">Links / 05</span>${heading("Take a closer", "look.")}<div class="project-links">${external("Visit website ↗", project.website, "button")}${external("Get on Google Play ↗", project.download, "button")}${external("Project Instagram ↗", project.instagram, "button")}${!project.website && !project.download ? "<p>In development — public links coming soon.</p>" : ""}</div></section>
    <a data-transition class="next-project" href="${projectPath(root, next.slug)}"><small>Next project / ${next.index}</small>${e(next.name)} ↗</a>`;
}

export function notFound(base) {
  return `<section class="project-hero not-found"><div class="project-hero__inner"><span class="eyebrow">404 / misplaced type</span><h1>Wrong page.</h1><p class="project-hero__tagline">The page you asked for is not in this edition.</p><a class="button" href="${base}index.html">Back to the front page →</a></div></section>`;
}
